# Generated by Django 5.0.1 on 2024-01-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_tag_artwork_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='tags',
        ),
        migrations.AddField(
            model_name='artwork',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
