# Generated by Django 5.0.1 on 2024-01-23 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_artwork_tags_artwork_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
